version: '3'
services:
  smartmetserver:
    image: smartmet-server
    container_name: smartmetserver
    labels:
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.smartmetserver.entrypoints=websecure"
      - "traefik.http.routers.smartmetserver.rule=Host(`data.vn.meteo.fi`)"
      - "traefik.http.services.smartmetserver.loadbalancer.server.port=8090"
    volumes:
      - /smartmet/cnf/server:/etc/smartmet/conf
      - /smartmet/data:/smartmet/data
      - /smartmet/share:/smartmet/share
    networks:
      traefik-network:
      smartmet-server-network:
        ipv4_address: 10.5.0.5
    restart: unless-stopped
  smartmet-server-db:
    image: smartmet-server-db
    container_name: smartmet-server-db
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    restart: always
    ports:
     - "5432:5432"
    volumes:
      - /smartmet/data/db:/var/lib/postgresql/data
    networks:
      smartmet-server-network:
        ipv4_address: 10.5.0.6

volumes:
  smartmetserver-storage-cnf:

networks:
  smartmet-server-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  traefik-network:
    external: true
      
