version: '3'
services:
  smartmetserver:
    image: fmidev/smartmetserver:latest
    container_name: smartmetserver
    labels:
      - "traefik.http.routers.smartmetserver.entrypoints=websecure"
      - "traefik.http.routers.smartmetserver.rule=Host(`data.vn.meteo.fi`)"
      - "traefik.http.services.smartmetserver.loadbalancer.server.port=8090"
    volumes:
      #- /smartmet/data/gfs/vietnam/surface/querydata/:/smartmet/data/gfs/surface
      #- /smartmet/data/gfs/vietnam/pressure/querydata/:/smartmet/data/gfs/pressure
      #- /smartmet/data/gem/vietnam/surface/querydata/:/smartmet/data/gem/surface
      #- /smartmet/data/gem/vietnam/pressure/querydata/:/smartmet/data/gem/pressure
      - /smartmet/cnf/server:/etc/smartmet
      - /smartmet/cnf/server:/etc/smartmet/conf
      - /smartmet/data:/smartmet/data
      - /smartmet/share:/smartmet/share
      #- smartmetserver-storage-cnf:/etc/smartmet
    networks:
      - traefik-network
      - smartmet-server-network
    restart: unless-stopped

volumes:
  smartmetserver-storage-cnf:

networks:
  smartmet-server-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  traefik-network:
    external: true
      
