version: '3'
services:
  smartmetalert:
    image: php:7.2-apache
    container_name: smartmetalert
    labels:
      - "traefik.http.routers.smartmetalert.entrypoints=websecure"
      - "traefik.http.routers.smartmetalert.rule=Host(`smartalert.nchmf.gov.vn`) && PathPrefix(`/smartalert`)"
      - "traefik.http.services.smartmetalert.loadbalancer.server.port=80"
    volumes:
      - /smartmet/www/:/var/www/html/
      - /smartmet/editor/smartalert:/var/www/html/smartalert/data
    networks:
      - traefik-network
          aliases: 
            - smartalert.nchmf.gov.vn
    restart: unless-stopped
    
networks:
    traefik-network:
      external: true
