version: '3'

services:
  geoweb:
    image: opengeoweb/geoweb
    container_name: geoweb
    restart: unless-stopped
    labels:
      - "traefik.http.routers.geoweb.entrypoints=websecure"
      - "traefik.http.routers.geoweb.rule=Host(`geoweb.apps.nchmf.gov.vn`)"
      - "traefik.http.services.geoweb.loadbalancer.server.port=8080"
    networks:
      - traefik-network
    volumes:
      - geoweb-storage:/usr/share/nginx/html/assets
  geoweb-backend-cap:
    image: registry.gitlab.com/opengeoweb/backend-services/cap-backend:main
    container_name: geoweb-backend-cap
    restart: unless-stopped
    labels:
      - "traefik.http.routers.geoweb-backend-cap.entrypoints=websecure"
      - "traefik.http.routers.geoweb-backend-cap.rule=Host(`geoweb-cap.apps.nchmf.gov.vn`)"
      - "traefik.http.services.geoweb-backend-cap.loadbalancer.server.port=8080"
    networks:
      - traefik-network
      
volumes:
  geoweb-storage:
  
networks:
    traefik-network:
      external: true
